pub mod data_model;
mod ontology;
pub mod property;
pub mod resource;
pub mod res_property;
pub mod label;
pub mod object;
mod builder;
pub mod dasch_list;
mod comment;
pub mod gui_element;
pub mod cardinality;
pub mod super_field_resource;
pub mod super_field_property;